FROM debian:stable

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get dist-upgrade -y --allow-downgrades
RUN apt-get install --no-install-recommends -y locales tzdata

# Set locale
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen
RUN dpkg-reconfigure --frontend=noninteractive locales
RUN update-locale LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8

#Install latest node for better compatibility with greenfield
RUN apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_21.x | bash -
RUN apt-get install -y nodejs
RUN npm install --global yarn

RUN apt-get install --no-install-recommends -y cmake build-essential ninja-build pkg-config libffi-dev libudev-dev libgbm-dev libdrm-dev libegl-dev libwayland-dev libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgraphene-1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-gl xwayland pipx libopengl-dev git autoconf libtool automake bison

RUN apt-get install -y --no-install-recommends \
    libffi8 \
    libudev1 \
    libgbm1 \
    libgraphene-1.0-0 \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-gl \
    libosmesa6 \
    libdrm2 \
    libopengl0 \
    libglvnd0 \
    libglx0 \
    libglapi-mesa \
    libegl1-mesa \
    libglx-mesa0 \
    xwayland \
    xauth \
    xxd \
    inotify-tools

RUN echo '#!/bin/sh -x\n\
for file in ls /patches/*; do\n\
  if ! patch -R -p1 -s -f --dry-run < "${file}" &> /dev/null; then\n\
    patch -p1 < "${file}"\n\
  fi\n\
done\n\
yarn install\n\
yarn workspaces foreach --parallel --topological-dev run build\n\
yarn workspace @gfld/compositor-proxy-cli package'\
> /build.sh
RUN chmod +x /build.sh

RUN mkdir /tmp/home
RUN chmod 777 /tmp/home
ENV HOME /tmp/home

RUN mkdir /opt/greenfield
WORKDIR /opt/greenfield
CMD ["/build.sh"]
