version: '3.6'
services:
  ums-client:
    build:
      context: ums-docker
      target: ums-client
    restart: always
    hostname: ums-client.local
    environment:
      - PUBLIC_HOSTNAME=jb-eng.de
    ports:
      - '10000:10000'
    volumes:
      - './ums-client-data:/root/.java/'
    devices:
      - '/dev/dri:/dev/dri'
    networks:
      ums:
        aliases:
          - ums-client.local
      web_and_certs_default:
        aliases:
          - ums-client.local

  ums-server:
    build:
      context: ums-docker
      target: ums-server
    restart: always
    hostname: wums.jb-eng.de
    ports:
      - '30001:30001'
      - '30005:30005/udp'
      - '30005:30005/tcp'
    volumes:
      - './ums-server-data:/opt/IGEL'
    networks:
      ums:
        aliases:
          - ums-server.local
      web_and_certs_default:
        aliases:
          - ums-server.local

networks:
  ums:
    name: ums-network
  web_and_certs_default:
    external: true
