version: '3.6'
services:
  ums-client:
    build:
      context: ums-docker
      target: ums-client
    restart: always
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - './greenfield:/opt/greenfield'
    devices:
      - '/dev/dri:/dev/dri'
    networks:
      - ums

  ums-server:
    build:
      context: ums-docker
      target: ums-server
    restart: always
    ports:
      - '8443:8443'
    networks:
      - ums

networks:
  ums:
    name: ums-network
